修复了 F2 快捷键失效的 bug.
lc6464/MyTan-Enhancer pull request #17
Opened 2024-09-06 13:47 UTC by KNWking

原本的快捷键失效的原因是因为原脚本通过触发 edit 键值来修改标题名，但新 UI 中将 edit 键值隐藏，只有在点击“更多”（key="btn-more"）后才会显现。

新触发逻辑是找到 active 的窗口下的 btn-more 并触发，在等待 100ms 后再触发 edit.

2024-09-08 07:35 UTC, KNWking commented
hello?

2024-09-08 09:28 UTC, lc6464 commented
今日新生开学，可能将于今晚或明天审核。

2024-09-09 04:12 UTC, lc6464 requested changes

2024-09-09 04:12 UTC, lc6464 commented on shortcut.user.js
> -			// Alt + A：切换到绘图模式
为何将这一个功能移除了？

2024-09-10 17:05 UTC, lc6464 reviewed
感谢贡献，请检查 setTimeout 是否必要，可以尝试直接连续执行两个模拟点击，如果能够稳定成功，请移除 setTimeout。

2024-09-11 10:31 UTC, KNWking commented
已经移除了不必要的延迟操作。

2024-09-11 11:05 UTC, lc6464 reviewed
非常感谢你的贡献，请你检查以下代码是否能够稳定工作，如果可以，请参照这一份代码进行修改。

2024-09-11 11:05 UTC, lc6464 commented
``` javascript
			// 获取当前活动对话的容器元素
			const activeConversation = document.querySelector('.active-conversation-item');
			if (activeConversation !== null) {
				// 在当前活动对话容器内点击“更多”按钮
				activeConversation.querySelector('svg-icon[key="btn-more"]')?.click();
				// 在当前活动对话容器内点击“编辑对话名称”按钮
				document.querySelector('svg-icon[key="edit"]')?.click();	
			}
```

2024-09-11 11:07 UTC, lc6464 commented
此外，你可以移除 Enter 键的确认功能，因为已经被官方实现。

2024-09-15 12:11 UTC, lc6464 approved these changes

2024-09-15 12:12 UTC, merged