Update README.md，超链接默认在新窗口打开。
lc6464/MyTan-Enhancer pull request #2
Opened 2024-06-16 02:49 UTC by KNWking

2024-06-16 04:45 UTC, lc6464 requested changes

2024-06-16 04:45 UTC, lc6464 commented on README.md
> +2. <a href="https://raw.githubusercontent.com/lc6464/MyTan-Enhancer/main/shortcut.user.js" target="_blank">点击此处</a> 安装 MyTan 补全计划脚本。
篡改猴的默认行为并不会导致点击此链接时原标签页被覆盖，此行没有修改的必要。

2024-06-16 04:45 UTC, lc6464 commented on README.md
> +本项目采用 MIT 许可证。详细信息请参阅 [LICENSE](LICENSE) 文件。
请不要过度修改格式。

2024-06-17 07:43 UTC, lc6464 commented
Hello?

2024-06-17 08:05 UTC, closed without merging

2024-06-17 08:05 UTC, KNWking commented
ok. 那直接 close 了。